### ISSUE TITLE
Pantalla 3 (journey-overview) template

### ISSUE THREAD

**Issue by yannicksprenger** [hardvolk/foodie-journal#7]
Crear y terminar el template de la pantalla 3

**Comment by edmundo096** [comment]
Creo que la pantalla 3 es el listado de los tracks (los Journeys).
El journey-overview es la pantalla 4 si mas no me equivoco.
No se a cual se refiere éste ticket.

La pantalla 3 de listado de tracks/journeys ya está terminada en el PR #10 a excepción de las Unit tests.
Le de un retoque al trabajo de quien sea "Papitomaster" haha.
